version: "3.2"

volumes:
  zigbee2mqtt-data:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/data/zigbee2mqtt/
      o: bind
  config:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/shared/smart-home-setup/kammer/config/
      o: bind
  shared:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/shared/smart-home-setup/shared/
      o: bind

services:
  # fan-control:
  #   restart: unless-stopped
  #   build:
  #     context: ../../fan-control
  #     args:
  #       - CACHE_DATE=2021-11-06
  #   hostname: fan-control
  #   cap_add:
  #     - SYS_RAWIO
  #   privileged: true
  #   devices:
  #     - /dev/mem:/dev/mem
  #   volumes:
  #     - config:/config:nocopy
  #     - globals:/globals:nocopy
  room-control-raspi:
    restart: unless-stopped
    build:
      context: ../../room-control-raspi
      args:
        - CACHE_DATE=2025-11-02
    hostname: room-control-raspi
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/mem:/dev/mem
    volumes:
      - shared:/globals:nocopy
    environment:
      - SMART_HOME_RASPI=kammer
      - SMART_HOME_CONFIG_PATH=../globals/config.js
      - SMART_HOME_TASKS=bad:dht22,bad:lights,bad:fans,bad:dht22,bad:lights,bad:fans,wc:dht22,wc:lights,wc:fans

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
        - zigbee2mqtt-data:/app/data
        - /run/udev:/run/udev:ro
    ports:
        # Frontend port
        - 8080:8080
    environment:
        - TZ=Europe/Berlin
    devices:
        # Make sure this matched your adapter location
        - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0008B86405-if00:/dev/ttyACM0
