version: "3.2"

volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/shared/smart-home-setup/kammer/config/
      o: bind
  globals:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/shared/smart-home-setup/globals/
      o: bind

services:
  fan-control:
    restart: unless-stopped
    build:
      context: ../../fan-control
      args:
        - CACHE_DATE=2021-11-06
    hostname: fan-control
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/mem:/dev/mem
    volumes:
      - config:/config:nocopy
      - globals:/globals:nocopy