version: "3.2"

volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/shared/smart-home-setup/kammer/config/
      o: bind
  shared:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/shared/smart-home-setup/shared/
      o: bind

services:
  # fan-control:
  #   restart: unless-stopped
  #   build:
  #     context: ../../fan-control
  #     args:
  #       - CACHE_DATE=2021-11-06
  #   hostname: fan-control
  #   cap_add:
  #     - SYS_RAWIO
  #   privileged: true
  #   devices:
  #     - /dev/mem:/dev/mem
  #   volumes:
  #     - config:/config:nocopy
  #     - globals:/globals:nocopy
  room-control-raspi:
    restart: unless-stopped
    build:
      context: ../../room-control-raspi
      args:
        - CACHE_DATE=2025-10-30
    hostname: room-control-raspi
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/mem:/dev/mem
    volumes:
      - shared:/globals:nocopy
    environment:
      - SMART_HOME_RASPI=arbeitszimmer
      - SMART_HOME_CONFIG_PATH=../globals/config.js
      - SMART_HOME_TASKS=bad:dht22,bad:lights,bad:fans,bad:dht22,bad:lights,bad:fans,wc:dht22,wc:lights,wc:fans