version: "3.2"

volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/shared/smart-home-setup/arbeitszimmer/config/
      o: bind

  globals:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/shared/smart-home-setup/globals/
      o: bind

  shared:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/shared/smart-home-setup/shared/
      o: bind

  smart-home-storage:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/data/smart-home-storage/
      o: bind

  mosquitto-data:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/data/mosquitto/data
      o: bind

  mosquitto-log:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/data/mosquitto/log
      o: bind

services:
  mosquitto:
    restart: always
    image: eclipse-mosquitto:2.0.3
    hostname: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  room-control-raspi:
    restart: unless-stopped
    build:
      context: ../../room-control-raspi
      args:
        - CACHE_DATE=2025-10-24.7
    hostname: room-control-raspi
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/mem:/dev/mem
    volumes:
      - shared:/globals:nocopy
    environment:
      - SMART_HOME_RASPI=arbeitszimmer
      - SMART_HOME_CONFIG_PATH=../globals/config.js
      - SMART_HOME_TASKS=schlafzimmer:dht22,schlafzimmer:shutters,kinderzimmer:shutters,arbeitszimmer:shutters,schlafzimmer:windows,kinderzimmer:windows,arbeitszimmer:windows,schlafzimmer:buttons,kinderzimmer:buttons,arbeitszimmer:buttons

  smart-home:
    restart: unless-stopped
    build:
      context: ../../smart-home
      args:
        - CACHE_DATE=2022-12-17
    hostname: smart-home
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/mem:/dev/mem
    volumes:
      - smart-home-storage:/storage
      - config:/config:nocopy
      - globals:/globals:nocopy


