version: "3.2"

volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: ./config
      o: bind

  config:
    driver: local
    driver_opts:
      type: none
      device: ../global
      o: bind

services:
  shutter-control:
    restart: unless-stopped
    build:
      context: shutter-control
      args:
        - CACHE_DATE=2020-02-08
    hostname: shutter-control
    ports:
      - 3000:3000
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/mem:/dev/mem
    volumes:
      - config:/config:nocopy
      - global:/global:nocopy