version: "3.2"

volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/shared/smart-home-setup/arbeitszimmer/config/
      o: bind
  globals:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/shared/smart-home-setup/globals/
      o: bind

  mosquitto-data:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/data/mosquitto/data
      o: bind

  mosquitto-log:
    driver: local
    driver_opts:
      type: none
      device: /home/pirate/data/mosquitto/log
      o: bind

services:
  mosquitto:
    restart: always
    image: eclipse-mosquitto:2.0.3
    hostname: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  shutter-control:
    restart: unless-stopped
    build:
      context: ../../shutter-control
      args:
        - CACHE_DATE=2021-12-31
    hostname: shutter-control
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/mem:/dev/mem
    volumes:
      - config:/config:nocopy
      - globals:/globals:nocopy

  smart-home:
    restart: unless-stopped
    build:
      context: ../../smart-home
      args:
        - CACHE_DATE=2021-11-07
    hostname: smart-home
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/mem:/dev/mem
    volumes:
      - config:/config:nocopy
      - globals:/globals:nocopy


